### PR TITLE
Fix action buttons to fill entire vertical and horizontal space of row

### LINKED ISSUE #82: Action buttons don't always fill available vertical space in row
### Expected behavior
Action buttons should always fill entire vertical and horizontal space of the row.

### Actual behavior
When action buttons in a row contain long descriptions, it will case the row to vertically expand. The other action buttons in the same row do not expand to fill that new space, causing each button to have differing heights.

Screen Shot 2020-07-10 at 11 49 40 AM

This was introduced in v3.4.0

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
Fixes #82

### CODE REVIEW

**Comment by Blackbaud-LindseyRix** [comment]
I'm not sure this is necessary as we're not going to use these action buttons much longer. We just need the search feature for the sky action buttons and then we plan to deprecate these. They are almost deprecated now.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-LindseyRix the skyux2-docs repo is going to be consuming the latest changes released in stache 3.4.0. If we do so, then the action buttons on the docs page will have the differing heights. Whats the recommended approach to get the latest from 3.4.0 without this bug?

**Comment by Blackbaud-LindseyRix** [comment]
Can you switch your action buttons over to your own SKY action buttons? That's what we've been doing is slowly start the process of converting over? If it's more work than you can do, I can have @Blackbaud-DeniseCisneros and I help you convert the SKY UX docs over.

**Comment by Blackbaud-AlexKingman** [comment]
It would be a considerable effort as we use stache action buttons in 15 places across the skyux2-docs SPA. With that said, I'm all for using the SKY UX action button - that seems to be in all of our best interest. 👍 

Just to be clear, this bug was released just a few days ago. If anyone upgrades their version 3 docs site with the latest stache (which happens every time you do a `skyux upgrade`), they'll get this bug. Wouldn't we want to prevent that? This PR doesn't change any functionality - its just simply a bug fix for what was just introduced.

**Comment by Blackbaud-LindseyRix** [comment]
A few things. We can accept this, but  we're deprecating our component immediately. @Blackbaud-DeniseCisneros is creating a SKY UX user story to switch over.

**Pull request merged**
