### PR TITLE
Update typography

### PR DESCRIPTION
**Pull request by Blackbaud-TimPepper**
Per design guidelines here: https://blackbaud.invisionapp.com/share/38R0GO6SETY#/screens/352009474

### CODE REVIEW

**Comment by Blackbaud-TimPepper** [comment]
> Values look correct to me. Is there a way to preview some Stache sites with these changes to make sure there aren't any unintented consequences?

I tested this in the Stache demo for this project, but I could pull it into another SPA to see if there is anything funky with it.

**Comment by Blackbaud-ToddRoberts** [comment]
It'd be good if we could look at it in another SPA - I'm mostly curious about whether we'll run into cases with a lot of Page Summary text where bumping it from 15 -> 19px will be noticeable. The SKYUX site would actually be a good test case, some of the component pages have long page summaries.

**Comment by Blackbaud-TimPepper** [comment]
> It'd be good if we could look at it in another SPA - I'm mostly curious about whether we'll run into cases with a lot of Page Summary text where bumping it from 15 -> 19px will be noticeable. The SKYUX site would actually be a good test case, some of the component pages have long page summaries.

Went ahead and tested this in one of the migrated Stache spas and it looks pretty good!

**Comment by Blackbaud-LindseyRix** [comment]
Can you post a screenshot Tim?

**Comment by Blackbaud-TimPepper** [comment]
> Can you post a screenshot Tim?

image

**Pull request merged**
